{% set name = "opentelemetry-instrumentation-aiohttp-client" %}
{% set version = "0.28b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfb17dad7c461a3a4e3fd2fec0d215b6ad3da3201968d174bc5d272326b7d65e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - aiohttp ~=3.0
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b1
    - python >=3.5
    - wrapt <2.0.0,>=1.0.0
    - opentelemetry-util-http ==0.28b1
    - opentelemetry-semantic-conventions ==0.28b1

test:
  imports:
    - opentelemetry.instrumentation.aiohttp_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiohttp-client
  summary: OpenTelemetry aiohttp client instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
