{% set name = "opentelemetry-instrumentation-aiohttp-client" %}
{% set version = "0.30b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5084d28af771b34faf44e553d98eddb0e29bc7a9055cb6071b4f1d32d157e5d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - aiohttp ~=3.0
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b0
    - python >=3.5
    - wrapt <2.0.0,>=1.0.0
    - opentelemetry-util-http ==0.30b0
    - opentelemetry-semantic-conventions ==0.30b0

test:
  imports:
    - opentelemetry.instrumentation.aiohttp_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiohttp-client
  summary: OpenTelemetry aiohttp client instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
